### ISSUE TITLE
用户登陆后显示用户名错误

### ISSUE THREAD

**Issue by DuckSoft** [wanghaiwei/bmie-cluster-frontend#2]
- ![default](https://user-images.githubusercontent.com/7822648/44627372-7681b780-a95f-11e8-97c2-6e4e3ac7a79f.png)
- ![default](https://user-images.githubusercontent.com/7822648/44627375-839ea680-a95f-11e8-831b-acf0de6b3c2b.png)
- ![default](https://user-images.githubusercontent.com/7822648/44627376-8a2d1e00-a95f-11e8-827a-832294aa0c30.png)

**Comment by wanghaiwei** [comment]
已修复
